(*
   If compiled with a version of https://github.com/ocaml/ocaml/pull/1951
   rebased on a recent trunk, one gets:

   File "./main.ml", line 117, characters 13-15:
   Error: During the typing of this pattern-matching,
          too many existentials were generated.
*)

type t =
  | C1 of int * int * int * int * int * int * int * int * int * int * int
  | C2: 'a -> t

let f = function
  | C1 (1, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (2, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (3, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (4, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (5, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (6, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (7, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (8, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (9, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (10, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (11, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (12, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (13, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (14, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (15, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (16, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (17, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (18, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (19, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (20, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (21, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (22, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (23, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (24, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (25, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (26, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (27, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (28, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (29, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (30, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (31, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (32, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (33, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (34, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (35, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (36, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (37, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (38, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (39, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (40, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (41, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (42, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (43, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (44, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (45, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (46, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (47, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (48, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (49, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (50, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (51, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (52, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (53, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (54, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (55, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (56, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (57, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (58, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (59, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (60, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (61, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (62, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (63, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (64, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (65, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (66, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (67, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (68, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (69, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (70, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (71, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (72, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (73, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (74, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (75, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (76, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (77, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (78, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (79, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (80, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (81, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (82, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (83, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (84, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (85, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (86, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (87, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (88, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (89, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (90, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (91, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (92, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (93, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (94, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (95, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (96, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (97, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (98, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (99, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (100, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (101, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C1 (102, a, b, c, d, e, f, g, h, i, j) -> ignore (a,b,c,d,e,f,g,h,i,j)
  | C2 _  -> ()
